config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "shellcheck"
version = "0.10.0"

[[plugin]]
name = "shfmt"
version = "3.8.0"

[[plugin]]
name = "actionlint"

[[plugin]]
name = "prettier"
